version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "bash", "-c", "test -f /var/www/migrations-done.txt"]
      interval: 5s
      timeout: 2s
      retries: 20
    command: >
      sh -c "
      sleep 5 &&
      until nc -z -v -w30 postgres 5432; do echo 'Waiting for database...'; sleep 1; done &&
      mkdir -p /var/www/bootstrap/cache /var/www/storage/logs &&
      chown -R www-data:www-data /var/www/bootstrap/cache /var/www/storage/logs &&
      chmod -R 775 /var/www/bootstrap/cache /var/www/storage/logs &&
      composer install &&
      php artisan config:clear &&
      php artisan migrate:fresh --seed &&
      touch /var/www/migrations-done.txt &&
      php artisan storage:link &&
      chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache &&
      chmod -R 775 /var/www/storage /var/www/bootstrap/cache &&
      supervisord -c /etc/supervisor/conf.d/supervisord.conf"

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laravel -h postgres || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_worker
    restart: always
    working_dir: /var/www
    volumes:
      - ./supervisor/worker.conf:/etc/supervisor/conf.d/worker.conf:ro
    depends_on:
      app:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - laravel_network
    command: sh -c "composer install && sleep 10 && supervisord -c /etc/supervisor/conf.d/worker.conf"


  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: adminer_ui
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - laravel_network
    environment:
      ADMINER_DESIGN: pepa-linha

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - laravel_network

volumes:
  postgres_data:

networks:
  laravel_network:
    driver: bridge
